"""
utils/pdf_exporter.py
Converts a Markdown research paper into a styled PDF using fpdf2.
Handles: headings, body text, bold, bullet points, references.
"""

import re
import os
from pathlib import Path
from fpdf import FPDF


OUTPUT_DIR = Path("output")


class ResearchPaperPDF(FPDF):
    """Custom FPDF class with styled header and footer."""

    def __init__(self, title: str = "Research Paper"):
        super().__init__()
        self.paper_title = title
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        if self.page_no() > 1:
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(120, 120, 120)
            self.cell(0, 8, self.paper_title[:80], align="C", new_x="LMARGIN", new_y="NEXT")
            self.ln(2)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")


def _clean_text(text: str) -> str:
    """Remove unsupported unicode characters for fpdf latin-1 encoding."""
    replacements = {
        "\u2019": "'", "\u2018": "'", "\u201c": '"', "\u201d": '"',
        "\u2013": "-", "\u2014": "--", "\u2026": "...", "\u00e9": "e",
        "\u00e8": "e", "\u00ea": "e", "\u00f1": "n", "\u00fc": "u",
        "\u00e4": "a", "\u00f6": "o", "\u03b1": "alpha", "\u03b2": "beta",
        "\u2192": "->", "\u2248": "~=", "\u221e": "inf", "\u03c0": "pi",
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    # Remove remaining non-latin1 characters
    return text.encode("latin-1", errors="ignore").decode("latin-1")


def markdown_to_pdf(
    markdown_text: str,
    topic: str,
    output_path: Optional[str] = None,
) -> str:
    """
    Convert markdown research paper to a styled PDF.
    
    Args:
        markdown_text: The paper in Markdown format
        topic: Paper topic (used for filename)
        output_path: Optional custom output path
    
    Returns:
        Path to the generated PDF file
    """
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    if output_path is None:
        safe_topic = "".join(c if c.isalnum() else "_" for c in topic.lower())[:40]
        output_path = str(OUTPUT_DIR / f"research_paper_{safe_topic}.pdf")

    # Extract title from markdown
    title = topic
    lines = markdown_text.strip().split("\n")
    for line in lines[:5]:
        if line.startswith("# "):
            title = line.lstrip("# ").strip()
            break

    pdf = ResearchPaperPDF(title=title[:80])
    pdf.add_page()

    # Title page
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(20, 40, 80)
    pdf.ln(10)

    # Word-wrap the title
    title_clean = _clean_text(title)
    pdf.multi_cell(0, 12, title_clean, align="C")
    pdf.ln(6)

    # Subtitle
    pdf.set_font("Helvetica", "I", 11)
    pdf.set_text_color(80, 80, 80)
    pdf.multi_cell(0, 8, f"Topic: {_clean_text(topic)}", align="C")
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 8, "Generated by Multi-Agent Research Paper Writer", align="C")
    pdf.ln(16)

    # Horizontal rule
    pdf.set_draw_color(20, 40, 80)
    pdf.set_line_width(0.5)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(10)

    # Process markdown content
    _render_markdown(pdf, markdown_text)

    pdf.output(output_path)
    return output_path


def _render_markdown(pdf: FPDF, markdown_text: str):
    """Render markdown content into the PDF."""
    lines = markdown_text.split("\n")
    i = 0

    while i < len(lines):
        line = lines[i].rstrip()

        # Skip title (already rendered)
        if line.startswith("# ") and i < 3:
            i += 1
            continue

        # H1
        if line.startswith("# "):
            text = _clean_text(line.lstrip("# ").strip())
            pdf.ln(6)
            pdf.set_font("Helvetica", "B", 16)
            pdf.set_text_color(20, 40, 80)
            pdf.multi_cell(0, 10, text)
            pdf.set_draw_color(20, 40, 80)
            pdf.set_line_width(0.3)
            pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
            pdf.ln(4)

        # H2
        elif line.startswith("## "):
            text = _clean_text(line.lstrip("# ").strip())
            pdf.ln(5)
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(30, 60, 120)
            pdf.multi_cell(0, 9, text)
            pdf.ln(2)

        # H3
        elif line.startswith("### "):
            text = _clean_text(line.lstrip("# ").strip())
            pdf.ln(3)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(50, 80, 140)
            pdf.multi_cell(0, 8, text)
            pdf.ln(1)

        # Horizontal rule
        elif line.startswith("---") or line.startswith("==="):
            pdf.ln(3)
            pdf.set_draw_color(180, 180, 180)
            pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
            pdf.ln(3)

        # Bullet points
        elif line.startswith("- ") or line.startswith("* "):
            text = _clean_text(line[2:].strip())
            text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)  # Remove bold
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(40, 40, 40)
            pdf.set_x(pdf.l_margin + 5)
            pdf.multi_cell(
                pdf.w - pdf.l_margin - pdf.r_margin - 5,
                6,
                f"  \u2022  {text}",
            )

        # Numbered lists
        elif re.match(r"^\d+\.\s", line):
            text = _clean_text(re.sub(r"^\d+\.\s", "", line).strip())
            text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(40, 40, 40)
            pdf.set_x(pdf.l_margin + 5)
            num = re.match(r"^(\d+)\.", line).group(1)
            pdf.multi_cell(
                pdf.w - pdf.l_margin - pdf.r_margin - 5,
                6,
                f"  {num}.  {text}",
            )

        # Bold line (standalone)
        elif line.startswith("**") and line.endswith("**") and len(line) > 4:
            text = _clean_text(line.strip("*"))
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(40, 40, 40)
            pdf.multi_cell(0, 7, text)

        # Empty line
        elif line.strip() == "":
            pdf.ln(3)

        # Normal paragraph
        else:
            text = _clean_text(line)
            # Strip markdown bold/italic for body
            text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
            text = re.sub(r"\*(.*?)\*", r"\1", text)
            text = re.sub(r"`(.*?)`", r"\1", text)
            if text.strip():
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(40, 40, 40)
                pdf.multi_cell(0, 6, text)

        i += 1


# Fix missing Optional import
from typing import Optional
